### ISSUE TITLE
Support with any web driver

### ISSUE THREAD

**Issue by Icyscools** [n0uur/sirify#1]
I found out this project uses Selenium to fetch lyrics on Spotify
and for using Selenium, we must have a web driver installed on our computer.
This project has used a Chrome driver for running Selenium.

But I think we should choose a web driver for running this project.
Could you please make support for any web driver (that Selenium supported) to running your project?

**Comment by n0uur** [comment]
you can just fork this repo and do it yourself :heart:

if you think that's will be useful for others people just make a pull request, I will review that later 😄
